# Generated by Django 2.2.1 on 2019-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibtex', models.TextField(verbose_name='Bibtex')),
                ('link', models.URLField(verbose_name='Link')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
    ]
